# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tracing.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'tracing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtracing.proto\x12\x07tracing\"\x8b\x02\n\nTraceEvent\x12\x14\n\x0ctimestamp_ns\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x32\n\x0bsource_type\x18\x03 \x01(\x0e\x32\x1d.tracing.TraceEventSourceType\x12+\n\nevent_type\x18\x04 \x01(\x0e\x32\x17.tracing.TraceEventType\x12\x10\n\x08sequence\x18\x05 \x01(\r\x12\x10\n\x08priority\x18\x06 \x01(\r\x12\x18\n\x0b\x64\x65\x61\x64line_ms\x18\x07 \x01(\x02H\x00\x88\x01\x01\x12\x19\n\x0cmarker_value\x18\x08 \x01(\rH\x01\x88\x01\x01\x42\x0e\n\x0c_deadline_msB\x0f\n\r_marker_value*R\n\x14TraceEventSourceType\x12\'\n#TRACE_EVENT_SOURCE_TYPE_UNSPECIFIED\x10\x00\x12\x07\n\x03ISR\x10\x01\x12\x08\n\x04TASK\x10\x02*\\\n\x0eTraceEventType\x12 \n\x1cTRACE_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x0e\n\nSPAN_START\x10\x01\x12\x0c\n\x08SPAN_END\x10\x02\x12\n\n\x06MARKER\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tracing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRACEEVENTSOURCETYPE']._serialized_start=296
  _globals['_TRACEEVENTSOURCETYPE']._serialized_end=378
  _globals['_TRACEEVENTTYPE']._serialized_start=380
  _globals['_TRACEEVENTTYPE']._serialized_end=472
  _globals['_TRACEEVENT']._serialized_start=27
  _globals['_TRACEEVENT']._serialized_end=294
# @@protoc_insertion_point(module_scope)
